DROP TABLE IF EXISTS Test;
DROP TABLE IF EXISTS Test;
DROP TABLE IF EXISTS t;
DROP TABLE IF EXISTS t;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
