CREATE SCHEMA "SCHEMA";
CREATE TYPE E AS ENUM('ALL');
CREATE TABLE "SCHEMA"."TABLE"("COLUMN" E);
INSERT INTO "SCHEMA"."TABLE" VALUES ('ALL');
DROP TABLE "SCHEMA"."TABLE";
CREATE TABLE "SCHEMA"."TABLE"("COLUMN" ROW("SOME" ROW("IN" INTEGER)));
INSERT INTO "SCHEMA"."TABLE" VALUES ({'some': {'in': 3}});
