SELECT b, sum(b) OVER (
    ORDER BY a NULLS LAST RANGE BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING
  )
FROM (
	SELECT CASE WHEN b < 70 THEN NULL ELSE 10 END AS a, b
	FROM range(1, 129) tbl(b)
	) t1
ORDER BY 1;
