DROP TABLE IF EXISTS test_table;
DROP TABLE IF EXISTS test_index;
DROP TABLE IF EXISTS test_index;
drop table if exists p;
create table pl (dt DateTime, i int, projection p (select sum(i) group by toStartOfMinute(dt))) engine MergeTree order by dt;
insert into pl values ('2020-10-24', 1);
drop table pl;
drop table if exists t;
create temporary table t (x UInt64, y alias x);
insert into t values (1);
