DROP TABLE IF EXISTS numbers1;
DROP TABLE IF EXISTS numbers2;
DROP TABLE IF EXISTS numbers3;
DROP TABLE IF EXISTS numbers4;
DROP TABLE IF EXISTS numbers5;
CREATE TABLE numbers1 ENGINE = StripeLog AS SELECT number FROM numbers(1000);
CREATE TABLE numbers2 ENGINE = TinyLog AS SELECT number FROM numbers(1000);
CREATE TABLE numbers3 ENGINE = Log AS SELECT number FROM numbers(1000);
CREATE TABLE numbers4 ENGINE = Memory AS SELECT number FROM numbers(1000);
CREATE TABLE numbers5 ENGINE = MergeTree ORDER BY number AS SELECT number FROM numbers(1000);
