drop table if exists dist_01756;
drop table if exists dist_01756_str;
drop table if exists dist_01756_column;
drop table if exists data_01756_str;
drop table if exists data_01756_signed;
system flush logs;
system flush logs;
system flush logs;
system flush logs;
create table data_01756_signed (key Int) engine=Null;
system flush logs;
