SELECT id, count(),
    minMerge(stringMin),
    maxMerge(stringMax),
    floor(minMerge(float64Min),5),
    floor(maxMerge(float64Max),5),
    floor(avgMerge(float64Avg),5),
    floor(sumMerge(float64Sum),5),
    floor(minMerge(float32Min),5),
    floor(maxMerge(float32Max),5),
    floor(avgMerge(float32Avg),5),
    floor(sumMerge(float32Sum),5),
    minMerge(decimal325Min),
    maxMerge(decimal325Max),
    avgMerge(decimal325Avg),
    sumMerge(decimal325Sum),
    minMerge(dateMin),
    maxMerge(dateMax),
    minMerge(datetimeMin),
    maxMerge(datetimeMax),
    minMerge(datetime64Min),
    maxMerge(datetime64Max),
    minMerge(int64Min),
    maxMerge(int64Max),
    avgMerge(int64Avg),
    sumMerge(int64Sum),
    minMerge(int32Min),
    maxMerge(int32Max),
    avgMerge(int32Avg),
    sumMerge(int32Sum),
    minMerge(int16Min),
    maxMerge(int16Max),
    avgMerge(int16Avg),
    sumMerge(int16Sum),
    minMerge(int8Min),
    maxMerge(int8Max),
    avgMerge(int8Avg),
    sumMerge(int8Sum)
FROM testNullableStatesAgg
GROUP BY id
ORDER BY id ASC;
