DROP TABLE IF EXISTS a1;
DROP TABLE IF EXISTS a2;
CREATE TABLE a1(a UInt8, b UInt8) ENGINE=Memory;
CREATE TABLE a2(a UInt8, b UInt8) ENGINE=Memory;
INSERT INTO a1 VALUES (1, 1), (1, 2), (2, 3);
INSERT INTO a2 VALUES (1, 2), (1, 3), (1, 4);
