create temporary table t1(a String);
create temporary table t2(a LowCardinality(String));
CREATE TEMPORARY TABLE a (x String);
CREATE TEMPORARY TABLE b (x LowCardinality(String));
CREATE TEMPORARY TABLE c (x Nullable(String));
CREATE TEMPORARY TABLE d (x LowCardinality(Nullable(String)));
INSERT INTO a VALUES ('hello');
INSERT INTO b VALUES ('hello');
INSERT INTO c VALUES ('hello');
INSERT INTO d VALUES ('hello');
