begin;
COMMIT;
COMMIT;
ROLLBACK;
COMMIT;
BEGIN;
COMMIT;
COMMIT;
BEGIN;
ROLLBACK;
COMMIT;
BEGIN;
COMMIT;
BEGIN;
ROLLBACK;
BEGIN;
COMMIT AND CHAIN;
COMMIT;
ROLLBACK;
ROLLBACK;
COMMIT;
ROLLBACK;
COMMIT;
COMMIT;
CREATE FUNCTION psql_error(msg TEXT) RETURNS BOOLEAN AS $$
  BEGIN
    RAISE EXCEPTION 'error %', msg;
  END;
$$ LANGUAGE plpgsql;
CREATE TABLE bla(s TEXT);                       -- succeeds
INSERT INTO bla VALUES ('Calvin'), ('Hobbes');
COMMIT;
BEGIN;
INSERT INTO bla VALUES ('Susie');         -- succeeds
COMMIT;
