create database if not exists shard_0;
create database if not exists shard_1;
drop table if exists shard_0.from_1;
drop table if exists shard_1.from_1;
drop table if exists shard_0.to;
drop table if exists shard_1.to;
system stop merges shard_0.from_1;
system stop merges shard_1.from_1;
drop table if exists shard_0.from_1;
drop table if exists shard_1.from_1;
