SHOW TABLES NOT LIKE '%';
SHOW TABLES;
CREATE TABLE test1 (x UInt8) ENGINE = Memory;
CREATE TABLE test2 (x UInt8) ENGINE = Memory;
SHOW TABLES;
SHOW TABLES LIKE 'tes%';
SHOW TABLES NOT LIKE 'tes%';
SHOW TABLES LIKE 'tes%1';
