DROP TABLE IF EXISTS src;
DROP TABLE IF EXISTS dst;
DROP TABLE IF EXISTS original_mv;
DROP TABLE IF EXISTS new_mv;
CREATE TABLE src (x UInt8) ENGINE = Null;
CREATE TABLE dst (x UInt8) ENGINE = Memory;
CREATE MATERIALIZED VIEW original_mv TO dst AS SELECT * FROM src;
INSERT INTO src VALUES (1), (2);
