create table "a.b.c" (x int);
describe "a.b.c";
create schema defg;
drop table "a.b.c";
create table defg."a.b.c" (x int);
describe defg."a.b.c";
drop table defg."a.b.c";
create table defg.abc (x int);
describe defg.abc;
drop table defg.abc;
drop schema defg;
create schema "d.e.f.g";
create table "d.e.f.g"."a.b.c" (x int);
describe "d.e.f.g"."a.b.c";
drop table "d.e.f.g"."a.b.c";
create table "d.e.f.g".abc (x int);
describe "d.e.f.g".abc;
CREATE TABLE integers(i INTEGER, j INTEGER, a INTEGER);
DESCRIBE;
DESCRIBE;
DROP TABLE integers;
create table t(plant text, dt date, mwh bigint);
DESCRIBE;
(DESCRIBE SELECT 42 AS a);
FROM (SHOW databases) t;
CREATE TABLE tbl AS SELECT 42 AS a;
create table "a.b.c" (x int);
summarize "a.b.c";
create schema defg;
drop table "a.b.c";
create table defg."a.b.c" (x int);
summarize defg."a.b.c";
drop table defg."a.b.c";
create table defg.abc (x int);
summarize defg.abc;
drop table defg.abc;
drop schema defg;
create table "d.e.f.g"."a.b.c" (x int);
summarize "d.e.f.g"."a.b.c";
drop table "d.e.f.g"."a.b.c";
summarize "d.e.f.g".abc;
CREATE TABLE integers(i INTEGER, j INTEGER);
CREATE TABLE integers2 (i INTEGER, j INTEGER, st VARCHAR, d DATE);
INSERT INTO integers VALUES (1, 1), (2, 2), (3, 3), (NULL, NULL);
INSERT INTO integers2 VALUES (1, 30, 'a', '1992-01-01'), (8, 12, 'b', '1992-01-01'), (3, 24, 'c', '1992-01-01'), (9, 16, 'd', '1992-01-01'), (10, NULL, 'e', '1992-01-01');
SHOW SELECT * FROM integers;
DESCRIBE SELECT * FROM integers;
SHOW SELECT i FROM integers;
SHOW SELECT integers.i, integers2.st, integers2.d FROM integers, integers2 WHERE integers.i=integers2.i;
SHOW SELECT SUM(i) AS sum1, j FROM integers GROUP BY j HAVING j < 10;
CREATE TABLE types(i INTEGER, j VARCHAR, k HUGEINT, d DOUBLE, e BLOB);
INSERT INTO types VALUES 
	(1, 'hello', 12, 0.5, BLOB 'a\x00b\x00c'), 
	(2, 'world', -12, -0.5, BLOB ''), 
	(3, NULL, NULL, NULL, NULL);
