DROP TABLE IF EXISTS test;
INSERT INTO TABLE FUNCTION file('01721_file/test/data.TSV', 'TSV', 'id UInt32') VALUES (1);
ATTACH TABLE test FROM '01721_file/test' (id UInt8) ENGINE=File(TSV);
INSERT INTO test VALUES (2), (3);
INSERT INTO test VALUES (4);
INSERT INTO test VALUES (5), (6);
