DROP DATABASE IF EXISTS `foo 1234`;
CREATE DATABASE `foo 1234`;
CREATE TABLE `foo 1234`.dict_data (key UInt64, val UInt64) Engine=Memory();
CREATE DICTIONARY `foo 1234`.dict
(
  key UInt64 DEFAULT 0,
  val UInt64 DEFAULT 10
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(HOST 'localhost' PORT tcpPort() USER 'default' TABLE 'dict_data' PASSWORD '' DB 'foo 1234'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT());
SYSTEM RELOAD DICTIONARY `foo 1234`.dict;
