drop table if exists distinct_in_order sync;
drop table if exists distinct_in_order sync;
drop table if exists distinct_in_order sync;
drop table if exists distinct_in_order sync;
drop table if exists distinct_cardinality_low sync;
drop table if exists distinct_in_order sync;
drop table if exists ordinary_distinct sync;
drop table if exists distinct_in_order sync;
drop table if exists ordinary_distinct sync;
drop table if exists distinct_in_order;
drop table if exists ordinary_distinct;
drop table if exists distinct_in_order;
drop table if exists ordinary_distinct;
drop table if exists distinct_cardinality_low;
drop table if exists sorting_key_empty_tuple;
drop table if exists sorting_key_contain_function;
