DROP TABLE IF EXISTS tab;
CREATE TABLE tab (id Int64, dflt Int64 DEFAULT 54321) ENGINE MergeTree ORDER BY id;
INSERT INTO tab (id, dflt) VALUES (1, 1);
INSERT INTO tab (id) VALUES (2);
ALTER TABLE tab MATERIALIZE COLUMN dflt;
DROP TABLE tab;
