BEGIN;
CREATE TABLE xacttest (a smallint, b real);
INSERT INTO xacttest VALUES
  (56, 7.8),
  (100, 99.097),
  (0, 0.09561),
  (42, 324.78);
INSERT INTO xacttest (a, b) VALUES (777, 777.777);
END;
BEGIN;
CREATE TABLE disappear (a int4);
DELETE FROM xacttest;
ABORT;
END;
BEGIN TRANSACTION READ ONLY;
END;
BEGIN TRANSACTION DEFERRABLE;
END;
CREATE TABLE writetest (a int);
CREATE TEMPORARY TABLE temptest (a int);
BEGIN;
COMMIT;
BEGIN;
SAVEPOINT x;
COMMIT;
BEGIN;
SAVEPOINT x;
COMMIT;
BEGIN;
SAVEPOINT x;
