DROP TEMPORARY TABLE IF EXISTS temp_tab;
CREATE TEMPORARY TABLE temp_tab (number UInt64);
EXISTS TEMPORARY TABLE temp_tab;
DROP TABLE temp_tab;
EXISTS TEMPORARY TABLE temp_tab;
CREATE TEMPORARY TABLE temp_tab (number UInt64);
