drop table if exists mt1;
drop table if exists mt2;
create table mt1 (n Int64) engine=MergeTree order by n;
create table mt2 (n Int64) engine=MergeTree order by n;
insert into mt1 values (1);
insert into mt2 values (10);
insert into mt1 values (2);
insert into mt2 values (20);
insert into mt1 values (3);
insert into mt2 values (30);
insert into mt1 values (4);
insert into mt2 values (40);
