create table "a.b.c" (x int);
describe "a.b.c";
create schema defg;
drop table "a.b.c";
create table defg."a.b.c" (x int);
describe defg."a.b.c";
drop table defg."a.b.c";
create table defg.abc (x int);
describe defg.abc;
drop table defg.abc;
drop schema defg;
create schema "d.e.f.g";
create table "d.e.f.g"."a.b.c" (x int);
describe "d.e.f.g"."a.b.c";
drop table "d.e.f.g"."a.b.c";
create table "d.e.f.g".abc (x int);
describe "d.e.f.g".abc;
CREATE TABLE integers(i INTEGER, j INTEGER, a INTEGER);
DESCRIBE;
DESCRIBE;
DROP TABLE integers;
create table t(plant text, dt date, mwh bigint);
DESCRIBE;
