CREATE TABLE IF NOT EXISTS integers(i INTEGER, j INTEGER);
CREATE TABLE IF NOT EXISTS integers(i INTEGER, j INTEGER);
CREATE TABLE IF NOT EXISTS integers2 AS SELECT 42;
CREATE TABLE IF NOT EXISTS integers2 AS SELECT 42;
DROP TABLE IF EXISTS integers;
DROP TABLE IF EXISTS integers;
DROP TABLE IF EXISTS no_such_scheme.integers;
