CREATE TABLE mytable(mycolumn INTEGER, myothercolumn INTEGER);;
SELECT "MYCOLUMN" FROM "MYTABLE";;
ALTER TABLE "MYTABLE" DROP COLUMN "MYCOLUMN";;
ALTER TABLE "MYTABLE" ADD COLUMN mycolumn INTEGER;;
ALTER TABLE "MYTABLE" ALTER COLUMN "MYCOLUMN" SET DEFAULT 3;
DROP TABLE "MYTABLE";
