CREATE SECRET (TYPE S3);
CREATE SECRET (TYPE S3, PROVIDER CONFIG);
CREATE SECRET (TYPE S3, PROVIDER CREDENTIAL_CHAIN);
CREATE SECRET (TYPE AZURE);
CREATE SECRET (TYPE AZURE, PROVIDER CONFIG);
CREATE SECRET (TYPE AZURE, PROVIDER CREDENTIAL_CHAIN);
