DROP TABLE IF EXISTS test_table;
CREATE TABLE test_table (id UInt64) ENGINE=TinyLog;
INSERT INTO test_table VALUES (0);
DROP DICTIONARY IF EXISTS test_dictionary;
CREATE DICTIONARY test_dictionary (id UInt64) PRIMARY KEY id LAYOUT(DIRECT()) SOURCE(CLICKHOUSE(TABLE 'test_table'));
